# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appironbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='senduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senduser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
