# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appironbank', '0002_auto_20160621_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balancemod',
            field=models.PositiveIntegerField(),
        ),
    ]
